### PR TITLE
Split the content of the site into small includes

### PR DESCRIPTION
**Pull request by nedSaf**
#27

### CODE REVIEW

**Comment by RoySegall** [comment]
Is this ready for merge?

**Comment by nedSaf** [comment]
No not yet.

**Comment by RoySegall** [comment]
OK. any way i think some is missing:
agency_parallax_responsive_html5_css3_template___fifo_themes

**Comment by nedSaf** [comment]
@RoySegall PR ready for code review.

**Comment by RoySegall** [comment]
@nader77 can you check this one:
selection_058

**Comment by nedSaf** [comment]
@RoySegall Fixed:
selection_046

**Comment by nedSaf** [comment]
@RoySegall Added sponsor logo:
selection_048

Issue #26

**Comment by nedSaf** [comment]
@RoySegall Added gizra logo:
selection_049

**Comment by nedSaf** [comment]
Merged.

**Pull request closed without merging**
