### PR TITLE
Mobile menu hide on click

### PR DESCRIPTION
**Pull request by nedSaf**
#19

### CODE REVIEW

**Comment by nedSaf** [comment]
@RoySegall PR is ready.

selection_015

**Comment by RoySegall** [comment]
_agency_parallax_responsive_html5_css3_template___fifo_themes
_agency_parallax_responsive_html5_css3_template___fifo_themes

**Comment by nedSaf** [comment]
Closed menu, Phone:
selection_021
Open menu, Phone:
selection_020

Open menu, Tablet:
selection_019

**Comment by nedSaf** [comment]
Merged.

**Comment by nedSaf** [comment]
Merged.

**Pull request merged**
